services:
  lazylang:
    build: .
    image: lazylang
    container_name: lazylang
    env_file:
      - .env
    environment:
      - PULSE_SERVER=/run/user/1000/pulse/native
    volumes:
      - /run/user/1000/pulse:/run/user/1000/pulse
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    group_add:
      - audio  
